# Generated by Django 3.2.7 on 2022-01-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=90)),
                ('bookname', models.CharField(max_length=90)),
                ('booknumber', models.CharField(max_length=90)),
            ],
        ),
    ]
